standalone_tags:
  [
    {id: 0, size: 0.2, name: "AprilTag_0"},
    {id: 1, size: 0.2, name: "AprilTag_1"},
    {id: 2, size: 0.2, name: "AprilTag_2"},
    {id: 3, size: 0.2, name: "AprilTag_3"}
  ]
